/* Scripts */
import themeJSON from '../../../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-build.js

export const theme: ThemeType = {
	breakpoints: themeJSON.breakpoint,
	colors: themeJSON.color,
};
